branch-defaults:
  main:
    environment: Mobius2-env
    group_suffix: null
environment-defaults:
  Mobius2-env:
    branch: null
    repository: null
global:
  application_name: mobius2
  branch: null
  default_ec2_keyname: mobius
  default_platform: Puma with Ruby 2.6 running on 64bit Amazon Linux
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
