branch-defaults:
  main:
    environment: east-env
global:
  application_name: west
  branch: null
  default_ec2_keyname: west
  default_platform: Ruby 2.7 running on 64bit Amazon Linux 2
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli2
  repository: null
  sc: git
  workspace_type: Application
